#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times, but for the 9th iteration
# , displays Holberton School and then Hi on a new line
export i=1
while ((i < 10))
do
    echo "Holberton School"
    ((i++))
    if [ "$i" == 9 ]
    then
	echo "Hi"
    fi
done
