#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times, but for the 9th iteration
export i=1
while ((i <= 10))
do
	if (( i == 4 ))
	then
		echo bad luck
	elif (( i == 8 ))
	then
		echo good luck
	else
		echo Holberton School
	fi
	(( i++ ))
done
