#!/usr/bin/env bash
# Bash script to run Nginx

pkill nginx
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 600
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start